package com.mijahel.backend.service;
import com.mijahel.backend.dto.TiendaDTO.*;import com.mijahel.backend.dto.ComercioDTO.*;import com.mijahel.backend.entity.*;import com.mijahel.backend.repository.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.core.env.Environment;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.transaction.support.TransactionTemplate;import org.springframework.transaction.PlatformTransactionManager;import java.util.*;import java.math.BigDecimal;import java.net.URI;import java.net.http.*;import java.util.concurrent.*;import tools.jackson.databind.ObjectMapper;import static org.junit.jupiter.api.Assertions.*;
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties="spring.jpa.show-sql=false")
class PedidoWebIT {
 @Autowired PedidoService service;@Autowired CuentaClienteService cuentasService;@Autowired ComercioService comercio;@Autowired PedidoRepository pedidos;@Autowired DetallePedidoRepository dp;@Autowired CuentaClienteRepository cuentas;@Autowired ProductoRepository productos;@Autowired ClienteRepository clientes;@Autowired VentaRepository ventas;@Autowired DetalleVentaRepository dv;@Autowired MovimientoInventarioRepository movimientos;@Autowired UsuarioRepository usuarios;@Autowired PasswordEncoder encoder;@Autowired Environment env;@Autowired ObjectMapper json;@Autowired PlatformTransactionManager manager;
 Usuario admin;Producto producto;Sesion sesion;List<UUID> cuentaIds=new ArrayList<>();String tokenAdmin;HttpClient http=HttpClient.newHttpClient();
 @BeforeEach void preparar()throws Exception{
  assertTrue(env.getProperty("spring.datasource.url","").endsWith("/gestor_mvp_test"));
  admin=new Usuario();admin.setUsername("pedidos-"+UUID.randomUUID());admin.setNombre("Administrador QA");admin.setEmail(UUID.randomUUID()+"@local.test");admin.setPasswordHash(encoder.encode("123456"));admin.setRol(Rol.ADMINISTRADOR);admin=usuarios.saveAndFlush(admin);
  tokenAdmin=json.readTree(req("POST","/api/auth/login",null,Map.of("username",admin.getUsername(),"password","123456")).body()).get("token").asText();
  producto=comercio.guardar(null,new ProductoRequest("PED-"+UUID.randomUUID(),"Memoria Kingston 16 GB","Memorias RAM","Kingston",new BigDecimal("500"),new BigDecimal("720"),10,2,true),admin);
  sesion=registrar();
 }
 Sesion registrar(){Sesion s=cuentasService.registrar(new Registro("Juan","Pérez",UUID.randomUUID()+"@local.test","Cliente123!","999999999","12345678"));cuentaIds.add(s.cuenta().id());return s;}
 @AfterEach void limpiar(){new TransactionTemplate(manager).execute(status->{for(var id:cuentaIds){for(var p:pedidos.findByCuentaIdOrderByFechaCreacionDesc(id)){var ms=movimientos.findAll().stream().filter(m->p.getId().equals(m.getPedidoId())).toList();movimientos.deleteAll(ms);dp.deleteAll(dp.findByPedidoId(p.getId()));UUID venta=p.getVentaId();pedidos.delete(p);pedidos.flush();if(venta!=null){dv.deleteAll(dv.findByVentaId(venta));ventas.deleteById(venta);}}CuentaCliente a=cuentas.findById(id).orElseThrow();cuentas.delete(a);cuentas.flush();clientes.deleteById(a.getClienteId());}for(var v:ventas.findAll().stream().filter(v->v.getVendedorId().equals(admin.getId())).toList()){movimientos.deleteAll(movimientos.findAll().stream().filter(m->v.getId().equals(m.getVentaId())).toList());dv.deleteAll(dv.findByVentaId(v.getId()));ventas.delete(v);}movimientos.deleteAll(movimientos.findAll().stream().filter(m->m.getProductoId().equals(producto.getId())).toList());productos.deleteById(producto.getId());usuarios.deleteById(admin.getId());return null;});}
 HttpResponse<String> req(String method,String path,String token,Object body)throws Exception{var b=HttpRequest.newBuilder(URI.create("http://localhost:"+env.getProperty("local.server.port")+path));if(token!=null)b.header("Authorization","Bearer "+token);if(body!=null)b.header("Content-Type","application/json");b.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body)));return http.send(b.build(),HttpResponse.BodyHandlers.ofString());}
 CrearPedido solicitud(int cantidad){return new CrearPedido(UUID.randomUUID(),List.of(new LineaRequest(producto.getId(),cantidad)));}
 int stock(){return productos.findById(producto.getId()).orElseThrow().getStock();}
 @Test void flujoCompletoHttpConPreciosServidorYConstancia()throws Exception{
  assertEquals(200,req("GET","/api/public/productos/"+producto.getSlug(),null,null).statusCode());
  CuentaCliente a=cuentas.findById(sesion.cuenta().id()).orElseThrow();assertNotEquals("Cliente123!",a.getPasswordHash());assertTrue(encoder.matches("Cliente123!",a.getPasswordHash()));
  assertEquals(200,req("POST","/api/tienda/auth/login",null,Map.of("email",a.getEmail(),"password","Cliente123!")).statusCode());
  CrearPedido r=solicitud(1);var resp=req("POST","/api/tienda/pedidos",sesion.token(),Map.of("clave",r.clave(),"lineas",r.lineas(),"total",1,"precio",1));assertEquals(200,resp.statusCode(),resp.body());var data=json.readTree(resp.body());UUID id=UUID.fromString(data.get("id").asText());String codigo=data.get("codigoRecojo").asText();assertTrue(codigo.matches("STR-\\d{8}-[A-Z2-9]{10}"));assertEquals(720,data.get("total").asInt());assertEquals(10,stock());
  assertEquals(id,service.crear(sesion.cuenta().id(),r).id());assertEquals(1,pedidos.findByCuentaIdOrderByFechaCreacionDesc(sesion.cuenta().id()).size());assertEquals(200,req("GET","/api/pedidos-web",tokenAdmin,null).statusCode());
  assertEquals(200,req("POST","/api/pedidos-web/"+id+"/confirmar",tokenAdmin,Map.of()).statusCode());assertEquals(9,stock());assertEquals(409,req("POST","/api/pedidos-web/"+id+"/confirmar",tokenAdmin,Map.of()).statusCode());
  assertEquals(200,req("POST","/api/pedidos-web/"+id+"/listo",tokenAdmin,Map.of()).statusCode());assertTrue(req("GET","/api/tienda/pedidos/"+id,sesion.token(),null).body().contains("LISTO_PARA_RECOGER"));assertTrue(req("GET","/api/pedidos-web/codigo?codigo="+codigo,tokenAdmin,null).body().contains(id.toString()));
  var entrega=req("POST","/api/pedidos-web/"+id+"/entregar",tokenAdmin,Map.of());assertEquals(200,entrega.statusCode(),entrega.body());assertEquals(9,stock());var p=pedidos.findById(id).orElseThrow();assertEquals("WEB",ventas.findById(p.getVentaId()).orElseThrow().getOrigen());assertEquals(1,dv.findByVentaId(p.getVentaId()).size());
  assertEquals(409,req("POST","/api/pedidos-web/"+id+"/entregar",tokenAdmin,Map.of()).statusCode());assertTrue(req("GET","/api/ventas",tokenAdmin,null).body().contains(p.getVentaId().toString()));var reporte=service.reporte("HOY");assertTrue(reporte.ventasWeb()>=1);assertTrue(reporte.importeWeb().compareTo(new BigDecimal("720"))>=0);
  for(int i=0;i<2;i++)assertTrue(req("GET","/api/tienda/pedidos/"+id,sesion.token(),null).body().contains("ENTREGADO"));assertEquals(1,pedidos.findByCuentaIdOrderByFechaCreacionDesc(sesion.cuenta().id()).size());
 }
 @Test void cancelacionDevuelveReservaYPosRespetaDisponibilidad(){var p=service.crear(sesion.cuenta().id(),solicitud(3));service.confirmar(p.id(),admin);assertEquals(7,stock());assertThrows(IllegalStateException.class,()->comercio.vender(new VentaRequest(UUID.randomUUID(),null,List.of(new LineaRequest(producto.getId(),8))),admin));var venta=comercio.vender(new VentaRequest(UUID.randomUUID(),null,List.of(new LineaRequest(producto.getId(),2))),admin);assertEquals("POS",venta.venta().getOrigen());assertEquals("Público general",venta.venta().getClienteNombre());assertEquals(5,stock());service.cancelar(p.id(),admin);assertEquals(8,stock());assertEquals("CANCELADO",service.propio(sesion.cuenta().id(),p.id()).estado());assertThrows(org.springframework.web.server.ResponseStatusException.class,()->service.entregar(p.id(),admin));assertEquals(2,movimientos.findAll().stream().filter(m->p.id().equals(m.getPedidoId())).count());}
 @Test void faltanteAntesDeCrearOConfirmarNoEscribe(){assertThrows(org.springframework.web.server.ResponseStatusException.class,()->service.crear(sesion.cuenta().id(),solicitud(11)));assertTrue(service.propios(sesion.cuenta().id()).isEmpty());var p=service.crear(sesion.cuenta().id(),solicitud(10));comercio.movimiento(new MovimientoRequest(producto.getId(),"SALIDA",1,"Prueba cambio de stock"),admin);assertThrows(org.springframework.web.server.ResponseStatusException.class,()->service.confirmar(p.id(),admin));assertEquals("PENDIENTE",service.propio(sesion.cuenta().id(),p.id()).estado());assertEquals(9,stock());service.cancelar(p.id(),admin);assertEquals(9,stock());}
 @Test void permisosCuentasYEstadosActuales()throws Exception{var p=service.crear(sesion.cuenta().id(),solicitud(1));var otra=registrar();assertEquals(404,req("GET","/api/tienda/pedidos/"+p.id(),otra.token(),null).statusCode());for(String path:List.of("/api/productos","/api/usuarios","/api/inventario","/api/reportes/resumen","/api/pedidos-web"))assertEquals(401,req("GET",path,sesion.token(),null).statusCode());assertEquals(401,req("GET","/api/tienda/cuenta",tokenAdmin,null).statusCode());assertEquals(404,req("GET","/api/pedidos-web/codigo?codigo=NO-EXISTE",tokenAdmin,null).statusCode());assertEquals(409,req("POST","/api/pedidos-web/"+p.id()+"/entregar",tokenAdmin,Map.of()).statusCode());var a=cuentas.findById(sesion.cuenta().id()).orElseThrow();var c=clientes.findById(a.getClienteId()).orElseThrow();c.setActivo(false);clientes.saveAndFlush(c);assertEquals(401,req("GET","/api/tienda/cuenta",sesion.token(),null).statusCode());}
 @Test void reintentoConcurrenteYEntregaConcurrenteNoDuplican()throws Exception{var r=solicitud(1);ExecutorService pool=Executors.newFixedThreadPool(2);try{var a=pool.submit(()->service.crear(sesion.cuenta().id(),r));var b=pool.submit(()->service.crear(sesion.cuenta().id(),r));UUID id=a.get(10,TimeUnit.SECONDS).id();assertEquals(id,b.get(10,TimeUnit.SECONDS).id());service.confirmar(id,admin);service.listo(id);Callable<Boolean> entrega=()->{try{service.entregar(id,admin);return true;}catch(org.springframework.web.server.ResponseStatusException e){return false;}};var e1=pool.submit(entrega);var e2=pool.submit(entrega);assertNotEquals(e1.get(10,TimeUnit.SECONDS),e2.get(10,TimeUnit.SECONDS));assertEquals(9,stock());assertEquals(1,ventas.findAll().stream().filter(v->v.getClave().equals(id)).count());}finally{pool.shutdownNow();}}
 @Test void rollbackReservaYEntregaNoDejanEscriturasParciales(){var p=service.crear(sesion.cuenta().id(),solicitud(1));var tx=new TransactionTemplate(manager);assertThrows(IllegalStateException.class,()->tx.execute(status->{service.confirmar(p.id(),admin);throw new IllegalStateException("Rollback de prueba");}));assertEquals(10,stock());assertEquals("PENDIENTE",service.propio(sesion.cuenta().id(),p.id()).estado());assertEquals(0,movimientos.findAll().stream().filter(m->p.id().equals(m.getPedidoId())).count());service.confirmar(p.id(),admin);service.listo(p.id());assertThrows(IllegalStateException.class,()->tx.execute(status->{service.entregar(p.id(),admin);throw new IllegalStateException("Rollback de prueba");}));assertEquals("LISTO_PARA_RECOGER",service.propio(sesion.cuenta().id(),p.id()).estado());assertNull(pedidos.findById(p.id()).orElseThrow().getVentaId());assertTrue(ventas.findByClave(p.id()).isEmpty());assertEquals(9,stock());}
 @Test void vendedorConsultaYEntregaPeroNoConfirmaNiPrepara()throws Exception{Usuario u=new Usuario();u.setUsername("pedido-vendedor-"+UUID.randomUUID());u.setNombre("Vendedor QA");u.setEmail(UUID.randomUUID()+"@local.test");u.setPasswordHash(encoder.encode("123456"));u.setRol(Rol.VENDEDOR);u=usuarios.saveAndFlush(u);try{String token=json.readTree(req("POST","/api/auth/login",null,Map.of("username",u.getUsername(),"password","123456")).body()).get("token").asText();var p=service.crear(sesion.cuenta().id(),solicitud(1));assertEquals(200,req("GET","/api/pedidos-web",token,null).statusCode());for(String accion:List.of("confirmar","listo","cancelar"))assertEquals(403,req("POST","/api/pedidos-web/"+p.id()+"/"+accion,token,Map.of()).statusCode());assertEquals(409,req("POST","/api/pedidos-web/"+p.id()+"/entregar",token,Map.of()).statusCode());}finally{usuarios.deleteById(u.getId());}}
}
