spring.datasource.url=${DATABASE_URL:jdbc:postgresql://${PGHOST}:${PGPORT:5432}/${PGDATABASE}}
spring.datasource.username=${DB_USERNAME:${PGUSER}}
spring.datasource.password=${DB_PASSWORD:${PGPASSWORD}}
app.jwt.secret=${JWT_SECRET}
app.web.allowed-origins=${FRONTEND_URL}
app.cors.allowed-origins=${FRONTEND_URL},app://gestion
app.productos.upload-dir=${UPLOAD_DIR}/productos
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
server.forward-headers-strategy=framework
server.error.include-message=never
server.error.include-stacktrace=never
