spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/gestor_db
spring.datasource.username=postgres
spring.datasource.password=postgres

app.jwt.secret=CambiaEstaClaveSecretaPorUnaMuyLargaYUnica1234567890ABCDEF
app.jwt.expiration-ms=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true